title: "Laer Innovation Inc."
description: "Leading the Way in Innovative Consulting"
baseurl: "" # Leave empty if hosted on root of domain
url: "https://laer-inc.github.io" # Update with your GitHub Pages URL
